### ISSUE TITLE
Text Overlaps with placeholder

### ISSUE THREAD

**Issue by ArunApsi** [hackiftekhar/IQDropDownTextField#101]
<img width="309" alt="Screenshot 2021-03-30 at 7 20 33 PM" src="https://user-images.githubusercontent.com/51071758/113000029-142f6a00-918d-11eb-9b00-c3eecc5dc807.png">

I'm facing this issue. text overlaps with placeholder.. Did anyone is facing this issue?

**Comment by hackiftekhar** [comment]
Can you please share a demo project? I don't  see this issue reproducible at my end.
