### ISSUE TITLE
The done button on the top bar is missing

### ISSUE THREAD

**Issue by mayooresan** [hackiftekhar/IQDropDownTextField#16]
Thanks for the awesome lib.

I tried implementing your library in my project as given in the readme file.

But the picker is showing up but no "Done" button is showing up in the view. Is it specific to iOS 8 ??

**Comment by hackiftekhar** [comment]
IQDropDownTextField is just for using UIPickerView for textField.inputView internally. It doesn't provide any functionality for done button. If you need so you can use IQDropDownTextField with IQKeyboardManager. You'll get automatic done button with IQKeyboardManager, You can dig in IQKeyboardManager demo project for IQDropDownTextField implementation.

**Comment by mayooresan** [comment]
@hackiftekhar Thanks for the headsup. Cheers.
