### ISSUE TITLE
Date and Time are current day/time instead of value in the field

### ISSUE THREAD

**Issue by kiahop** [hackiftekhar/IQDropDownTextField#17]
Is there a way to have the default value to be what is in the text field?  for example, using IQDropDown to control a date field, and the date field has a value, say '01/06/2006', the selector comes up selecting today's date.  How can it come up doing at '01/06/2006/?

**Comment by hackiftekhar** [comment]
You can use it's setter method to set date after setting pickerMode.

On Wednesday, March 11, 2015, kiahop <notifications@github.com> wrote:

> Is there a way to have the default value to be what is in the text field?
> for example, using IQDropDown to control a date field, and the date field
> has a value, say '01/06/2006', the selector comes up selecting today's
> date. How can it come up doing at '01/06/2006/?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQDropDownTextField/issues/17>.
>


-- 
Sent from My iPhone

**Comment by kiahop** [comment]
Works like a charm.  Thanks
