### ISSUE TITLE
The method of UITextFieldDelegate won't work

### ISSUE THREAD

**Issue by bestwnh** [hackiftekhar/IQDropDownTextField#21]
For 1.0.5 the IQDropDownTextField just delegate its own delegate method `-(void)textField:(IQDropDownTextField*)textField didSelectItem:(NSString*)item;`, all method in UITextFieldDelegate won't work.

I already create a pull request to fix this.https://github.com/hackiftekhar/IQDropDownTextField/pull/20
Hope this fix can bump to 1.0.5.1 ASAP for cocoapod.

**Comment by bestwnh** [comment]
@hackiftekhar Any progress on this?

**Comment by hackiftekhar** [comment]
@bestwnh Sorry, didn't get time to look this. I need to check the code. Will let you know my feedback soon.

**Comment by bestwnh** [comment]
Thank you for reply so soon. You can check my request https://github.com/hackiftekhar/IQDropDownTextField/pull/20 This will work fine.
It just about the different between @synthesize and @dynamic. A simple way to explain:
@synthesize mean you set up all related code.
@dynamic mean if you won't set up some code, it would inherit from parent class.

**Comment by hackiftekhar** [comment]
Yes, you're right. Just merged pull request.

**Comment by FaridHaddad** [comment]
hello, its still not working for me .. the delegate does not responds to the selector textField:didSelectItem: .. and the delegate is @dynamic .. what to do please ? thank you

**Comment by bestwnh** [comment]
Could you provide the sample code and the version of IQDropDownTextField you use? Is it other delegate method work?

**Comment by hackiftekhar** [comment]
I checked the demo and this delegate is working for me. You just need to assign textfield.delegate = self;

**Comment by FaridHaddad** [comment]
timeTextField.isOptionalDropDown = false
        timeTextField.itemList = ["15 mins","30 mins","45 mins","1h","1h 15mins","1h 30mins","1h 45mins","2h"]
        timeTextField.delegate = self

func textField(textField: IQDropDownTextField, didSelectItem item: String?) {
       // this func does not trigger ..
    }

**Comment by FaridHaddad** [comment]
its done .. i change the place of timeTextField.delegate = self from viewDidLoad to viewWillAppear ... it worked

**Comment by hackiftekhar** [comment]
Not sure what was the issue but it should work with viewDidLoad too.

**Comment by manishvpatel** [comment]
I have set textfield in UITableviewCell but didSelectItem does not work. can you please help me out of this or any alternate available?
