### ISSUE TITLE
using in UITableViewCell

### ISSUE THREAD

**Issue by ZhuchoG** [hackiftekhar/IQDropDownTextField#22]
Hello, i trying to use this field in table view cell, but it crashed all Xcode :) is this only me or anyone else
```swift
import UIKit
class JTVCDropDownCell: JTVCCell
{
    @IBOutlet weak var dropDownTextField: IQDropDownTextField!
    override func update(data: AnyObject)
    {
        if let items = data as? NSArray
        {
            dropDownTextField.isOptionalDropDown = false
            dropDownTextField.itemList = items as [AnyObject]
        }
    }
}
```

**Comment by bestwnh** [comment]
Please provide more related code or just put it in a simple view and find out the issue is about the cell or any other code, I use it in table view cell and work just fine.

**Comment by ZhuchoG** [comment]
That is all what i did, JTCCell is just UITableViewCell with definition of update(). In clear view it works just fine. If remove IQDropDownTextField from this code, all working as i see. IQDropDownTextField i install from cocoapods.

**Comment by bestwnh** [comment]
What kind of Class in your "items"? It should be a [NSString] array. Correct?

**Comment by ZhuchoG** [comment]
Correct :) i will try one thing tonight, think will resolve.

**Comment by ZhuchoG** [comment]
Yes, i forget registerNib :) sorry, all is ok
