### ISSUE TITLE
Latest version doesn't call UITextFieldDelegate Methods.

### ISSUE THREAD

**Issue by DMCApps** [hackiftekhar/IQDropDownTextField#23]
Hello, 

I am using your pod within my application. I have come across an issue in the latest version which prevents the UITextFieldDelegate methods of my controller from running. Hence I am not able to validate text entries during text changes.

Thanks.

**Comment by nbfuhao** [comment]
```IQDropDownTextField``` defined ```IQDropDownTextFieldDelegate```. So I think if you are trying to use UITextFieldDelegate in your controller, and assign it to an instance of ```IQDropDownTextField```, it will complain "incompatible type"

**Comment by hackiftekhar** [comment]
IQDropDownTextFieldDelegate Protocol is Inherited from UITextFieldDelegate and override delegate ptoperty. Have you checked this library code before posting your comment?

**Comment by nbfuhao** [comment]
I deleted my comment to avoid confusion.

**Comment by hackiftekhar** [comment]
My intention was not to ask you to delete your comment, problem was mine to not update anything about this issue. I think this is already fixed, I'll push latest version to cocoapods and will close this issue.
