### ISSUE TITLE
Cannot get rid of picker

### ISSUE THREAD

**Issue by redbrain** [hackiftekhar/IQDropDownTextField#26]
I am unsure how you get rid of the picker. When uipicker is presented with the items i am unable to get it to go away. And cannot find a method to close it on the selection delegate.

**Comment by hackiftekhar** [comment]
IQDropDownTextField is subclass of UITextField. You can resign it like a normal textField by calling resignFirstResponder.

**Comment by redbrain** [comment]
Awh thanks that works!
