### ISSUE TITLE
TextField's text on init

### ISSUE THREAD

**Issue by lfarah** [hackiftekhar/IQDropDownTextField#27]
I think that the textfield should init with "", not the first item on the array. With this, the user can see the Placeholder before tapping on the textfield.

What do you think?

By the way, our repo ROCKS!

**Comment by hackiftekhar** [comment]
May be you're right. But I need to check if 'isOptional' property doesn't break.

**Comment by hackiftekhar** [comment]
Could you please let me know which line or portion of code you are referring? I tried to take a look, but can't find something useful.

**Comment by darkFunction** [comment]
Please could you reopen this- it's a valid requirement, the user can no longer see the placeholder text

**Comment by hackiftekhar** [comment]
I can reopen, but no one replied to my comment. That's why I closed this issue.

**Comment by darkFunction** [comment]
All good :) I just noticed this problem myself which is why I commented. Since 'text' was deprecated the placeholder text doesn't work

**Comment by darkFunction** [comment]
Actually, I was missing the `isOptionalDropDown` BOOL. Sorry.
