### ISSUE TITLE
Bar to close dropdown doesn't appear

### ISSUE THREAD

**Issue by woolardjason** [hackiftekhar/IQDropDownTextField#28]
It appears that the bar to close the dropdown doesn't appear like shown in your screenshots. I'm testing with 8.4 if that helps and the Objective-C code. Otherwise great job, I will be using this in a lot of my upcoming projects if I can fix that issue. :-) Saves me a lot of time

**Comment by hackiftekhar** [comment]
You have to manually add UIToolbar as inputAccessoryView for textField, otherwise you can also use my IQKeyboardManager library for automatic UIToolbar for all textField.
