### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by jaredMermey** [hackiftekhar/IQDropDownTextField#31]
Can you please put up an example Swift project?

**Comment by hackiftekhar** [comment]
It's already there in demo project. Tou'll find two target. One with ObjC and other one with swift.

**Comment by hackiftekhar** [comment]
Ohh sorry, I thought you were asking about my otger library. No problem, I'll update Read me file.

**Comment by hackiftekhar** [comment]
Actually I don't think that I should put an example, because most of the developers know how to use Objective-C code with swift projects.

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
