### ISSUE TITLE
Optional row is 0 or -1 ?

### ISSUE THREAD

**Issue by fmaylinch** [hackiftekhar/IQDropDownTextField#34]
When `isOptionalDropDown` is `YES` you have that:

* `selectedRow` returns -1 when the optional row is selected.
* To set the optional row you need to assign `selectedRow = 0`.

I'd prefer to set `selectedRow = -1` for consistency.

**Comment by hackiftekhar** [comment]
Yup, I need to fix it. Thanks

**Comment by fmaylinch** [comment]
Thanks for the component, @hackiftekhar.

I also suggest to show more features in the sample code, like `optionalItemText` or `IQDropDownTextFieldDelegate`. They are really handy.

**Comment by hackiftekhar** [comment]
Hmm, you are right. Will update demo
Code too. Would you like to any other features in demo? I'll add them in one shoot.

**Comment by fmaylinch** [comment]
I'm using those, but please add anything that may be interesting to use.
Thanks!
