### ISSUE TITLE
Since `setText` was deprecated, there is no way of having different text in the dropdown & textfield

### ISSUE THREAD

**Issue by darkFunction** [hackiftekhar/IQDropDownTextField#35]
For example, in the drop down menu I need:

`
13, 14, 15 
...
`

But when the user selects one, I want to be able to set the text to:

`13 years old`

**Comment by hackiftekhar** [comment]
That's logically doesn't make sense. If you like to show 13 years old, 14 years old, 15 years old then dropdown should display exactly same thing.

**Comment by ryanheitner** [comment]
I think it is a valid use case to want different text, in my case I want the opposite to darkfunction, have the picker show 60 minutes but I only have space in the text field to show 60.

**Comment by hackiftekhar** [comment]
ok, then I think we can add some functionality to show text from different array and picker shows different array.
