### ISSUE TITLE
DatePicker Date Issue

### ISSUE THREAD

**Issue by kuldeep13990** [hackiftekhar/IQDropDownTextField#38]
selected date from date picker is 25/12/2015 , and when i pass that selected date in data base the date is 24/12/2015.

i think it's because of different time zone, so i try the following
[self.dropDownDateFormatter setTimeZone:[NSTimeZone timeZoneForSecondsFromGMT:0]];

but still i receive wrong date from picker.

any solution please.

Thanks in Advance.

**Comment by hackiftekhar** [comment]
You can manually convert the returned date according to your device
tomezone, but I'll take a look
