### ISSUE TITLE
Exists a way to show the done button?

### ISSUE THREAD

**Issue by juancholt** [hackiftekhar/IQDropDownTextField#40]
When the dropdown picker is shown the bar that goes over the picker view and haves a done button isnt showing, exists any sort of method to show that like the image you've posted?

**Comment by hackiftekhar** [comment]
Actually it's developer responsibility add add a toolbar with done button above picker. You can compare this issue with the native iOS keyboard problem. When a keyboard up and there is developer responsibility to dismiss keyboard when return button is pressed.

**Comment by svbalamuruga** [comment]
fileprivate lazy var allTextFields: [IQDropDownTextField] = {
        let allTextFields: [IQDropDownTextField] = [
            self.header_style
        ]
        return allTextFields
    }()
        override func viewDidLoad() {
        super.viewDidLoad()
        
            let flexibleButton = UIBarButtonItem(barButtonSystemItem: .flexibleSpace, target: nil, action: nil)
            let doneButton = UIBarButtonItem(title: "Done", style: .plain, target: self, action: #selector(doneClicked(_:)))
            let toolbar = UIToolbar()
            toolbar.items = [flexibleButton, doneButton]
            toolbar.sizeToFit()
            
            self.allTextFields.forEach { (textField) in
                textField.inputAccessoryView = toolbar
            }
