### ISSUE TITLE
Set IQDropDown Default Text

### ISSUE THREAD

**Issue by kuldeep13990** [hackiftekhar/IQDropDownTextField#43]
i am trying to set default value to iqDropDownTextField like Male or Female. but i am not able to set default string

txt gender.selecteditem = @"Male";

any solution please.
thanks in advance...

**Comment by hackiftekhar** [comment]
You need to first set the array for items then you should set selectedItem, it should work. If it's not then I need to look into this.

**Comment by kuldeep13990** [comment]
i just want to set single word in iqDropDownTextfield like normal textfield.. theres no array

**Comment by hackiftekhar** [comment]
Then you must have to provide an array of one object

**Comment by kuldeep13990** [comment]
i will try.. ok thanks...
