### ISSUE TITLE
Jumps to wrong index when using optional drop down

### ISSUE THREAD

**Issue by meismyles** [hackiftekhar/IQDropDownTextField#47]
When using `isOptionalDropDown = true` in either Objective-C or Swift, when selecting a row, the picker immediately jumps to the next row (meaning you can never select the bottom row) and thus the text field text is incorrect.

**Comment by meismyles** [comment]
Submitted a pull request that fixes this: https://github.com/hackiftekhar/IQDropDownTextField/pull/48

**Comment by hackiftekhar** [comment]
ok, I'll check it first before merging. Thanks for the PR.

**Comment by Lawrence2359** [comment]
facing the same issue as well, when isOptionalDropDown is false or true also will jump index!

**Comment by meismyles** [comment]
@Lawrence2359 I've submitted a pull request with a fix, but you can check out my fork [here](https://github.com/meismyles/IQDropDownTextField) which fixes it until the request is looked at.

**Comment by hackiftekhar** [comment]
This is merged now and 1.0.9 is released with the fix.
