### ISSUE TITLE
Not showing bar buttons

### ISSUE THREAD

**Issue by lfarah** [hackiftekhar/IQDropDownTextField#58]
<img width="470" alt="screen shot 2016-07-06 at 4 13 37 pm" src="https://cloud.githubusercontent.com/assets/6511079/16631262/a249a356-4394-11e6-9fa3-08b9803465c4.png">

**Comment by hackiftekhar** [comment]
It's upto the developer to show a toolbar over pickerView or not.

**Comment by lfarah** [comment]
Oh I thought that since there was a whitespace there, it was a bug since a toolbar is shown on the ```Readme.md```:
<img width="376" alt="screen shot 2016-07-11 at 12 21 09 am" src="https://cloud.githubusercontent.com/assets/6511079/16719129/6e17f63e-46fd-11e6-8eb7-7c287c18bd2a.png">

How do I show it ?

**Comment by hackiftekhar** [comment]
You could add UIToolbar as inputAccessoryView.
