### ISSUE TITLE
open IQDropDownTextField programmatically

### ISSUE THREAD

**Issue by brunoteixeiralc** [hackiftekhar/IQDropDownTextField#59]
In my code in certain point I want to open my IQDropDownTextField without need to click in my textfield.

There is any way to do this?

For example : load my data e than open my IQDropDownTextField populate with this data.

**Comment by raducanb** [comment]
Hi. Send the `becomeFirstResponder` message to your IQDropDownTextField after your data loads.

**Comment by hackiftekhar** [comment]
Thanks @raducanb for responding so quickly. :)
