### ISSUE TITLE
Support For custom objects in Item list Array.

### ISSUE THREAD

**Issue by swayam007** [hackiftekhar/IQDropDownTextField#60]
Can you provide support for item list array with custom model objects with specified with key.
For e.g Array of Users objects with specified with key "user_name".  So it is easy to get User object when item was selected.

**Comment by hackiftekhar** [comment]
I think your situation can easily be handled by getting an array of user_name and set it to itemList. I don't think it should be supported by library since same feature can be achieved by existing feature but with a little bit more code.
