### ISSUE TITLE
Time picker is broken once minimumDate is set

### ISSUE THREAD

**Issue by djbe** [hackiftekhar/IQDropDownTextField#61]
If you set the minimumDate to (for example) `2001-01-01 17:00:00`, whenever you try to pick a time, it will scroll back to the minimum time. I think that in #54, besides hitting the lolale/timezone issue, they were also hitting this issue (see comment from @lecksfrawen).

The reason is that when you pick a time, for example 17:30, the following will happen:

1. `timePicker`'s date property is changed to `2001-01-01 17:30:00` (from picking)
2. `timeChanged:` is called with `2001-01-01 17:30:00`
3. `dropDownTimeFormatter` is used to convert the date to `"17:30"`
3. `setSelectedItem:` is called with `"17:30"`
4. the string is parsed using `dropDownTimeFormatter` as a date into `2000-01-01 17:30:00`
5. the `timePicker`'s date property is set to `2000-01-01 17:30:00` using `setDate:animated:`
6. since this new date date is before the `minimumDate` of `2001-01-01 17:00:00`, the picker scrolls back to `"17:00"`

This whole issue stems from the fact that all dates are continually being converted between `NSString`s and `NSDate`s, which is quite inefficient on top of sometimes breaking some dates. This root problem should be solved, but involves rewriting quite a few methods.

A quick fix for this specific issue would be changing this line:

```Objective-C
NSDate *date = [self.dropDownTimeFormatter dateFromString:selectedItem];
```

to this:

```Objective-C
NSDate *date = [self.dropDownTimeFormatter dateFromString:selectedItem];
NSDateComponents *components = [[NSCalendar currentCalendar] components: NSCalendarUnitMonth | NSCalendarUnitDay | NSCalendarUnitHour | NSCalendarUnitMinute | NSCalendarUnitSecond fromDate:date];
components.year = 2001;
date = [[NSCalendar currentCalendar] dateFromComponents: components];
```

**Comment by hackiftekhar** [comment]
Great findings @djbe, I'll take a look and will check kf we can ignore minimumDate in case of time picker.

**Comment by djbe** [comment]
Thing is, the UIDatePicker component (and its minimumDate) works correctly. It is the transformation from Date --> String --> Date that breaks things.

If you want I can create a pull request with proposed solution.

**Comment by hackiftekhar** [comment]
Please create a PR

**Comment by djbe** [comment]
Thanks!
