### ISSUE TITLE
How to observe the change of IQDropDownTextField's text

### ISSUE THREAD

**Issue by yanyoung** [hackiftekhar/IQDropDownTextField#64]
```
[self.textFieldTextPicker addTarget:self action:@selector(sportTypeDidChanged) forControlEvents:UIControlEventEditingChanged];

-(void)sportTypeDidChanged
{
    self.remark.text = self.textFieldTextPicker.text;
}
```

I want to change `self.remark.text` after `self.textFieldTextPicker.text `changed. but code above cannot work. Any help would be greatly appreciated. Thanks!

**Comment by hackiftekhar** [comment]
You could implement `textField:didSelectItem:` delegate method to get callback when any changes made on picker.
