### ISSUE TITLE
setting formatter to date picker not working

### ISSUE THREAD

**Issue by sameer4** [hackiftekhar/IQDropDownTextField#66]
i'm setting the formatter to a dropdown in datepicker mode.it show the correct format in textfield when a date is selected but not showing new format in dropdown gear
![screen shot 2017-04-17 at 7 12 38 pm](https://cloud.githubusercontent.com/assets/6317374/25091298/da0e119e-23a1-11e7-9076-70c32e59c8f2.png)

`NSDateFormatter *formatter = [[NSDateFormatter alloc] init];`
 `[formatter setDateFormat:@"EEE MMMM dd yyyy"];`
 `[cell.txtBeginningDay setDateFormatter:formatter];`
 `cell.txtBeginningDay.dropDownMode = IQDropDownModeDatePicker;`
 `cell.txtBeginningDay.isOptionalDropDown = YES;`

**Comment by hackiftekhar** [comment]
@sameer4 It's showing correct format, you set @"EEE MMMM dd yyyy"] and it's showing "Sun September 17 2017" and you selected same date. Can you please reword your question so that I can better understand?

**Comment by sameer4** [comment]
@hackiftekhar  i wanted it to show **Sun September 17 2017** in picker instead of textfield

**Comment by hackiftekhar** [comment]
hmm, then we can't do anything much. We already exposing UIDatePicker object, and you can only change it's mode
```
typedef NS_ENUM(NSInteger, UIDatePickerMode) {
    UIDatePickerModeTime,           // Displays hour, minute, and optionally AM/PM designation depending on the locale setting (e.g. 6 | 53 | PM)
    UIDatePickerModeDate,           // Displays month, day, and year depending on the locale setting (e.g. November | 15 | 2007)
    UIDatePickerModeDateAndTime,    // Displays date, hour, minute, and optionally AM/PM designation depending on the locale setting (e.g. Wed Nov 15 | 6 | 53 | PM)
    UIDatePickerModeCountDownTimer, // Displays hour and minute (e.g. 1 | 53)
} __TVOS_PROHIBITED;
```
It's limited to show the things in date picker and not possible to customize that one.

**Comment by sameer4** [comment]
yes i know with datepicker of ios it's not possible unless we make a custom picker populated with dates and time data.

**Comment by hackiftekhar** [comment]
So @sameer4 whats the requirement now?

**Comment by sameer4** [comment]
he wanted this formate in dropdown gear.i didn't have the time make a custom one.so i asked him it's not possible.

**Comment by hackiftekhar** [comment]
So the final result is that it's not possible for my library to customize that and there is no such plans to do that.

**Comment by sameer4** [comment]
i think you should work on it when you are free.i didn't find any library to support custom formatter in date picker.will be a great help for future if some one need it.

**Comment by hackiftekhar** [comment]
I don't have any plans to do it, since it's general requirement to support standard date picker UI supported by iOS. But it's a rare case requirement to support any custom formatter. Also it will be too much work to support a feature which will rarely be used.

If you are still interested to see this feature in this library then can you work on this when you have free time and make a pull-request?

**Comment by hackiftekhar** [comment]
@sameer4 Will you work on this feature when you have some free time?

**Comment by sameer4** [comment]
ok i will when i will be free.not sure when.
