### ISSUE TITLE
IQKeyboardManager with IQDropDownTextField facing problems

### ISSUE THREAD

**Issue by Prabhat-Emorphis** [hackiftekhar/IQDropDownTextField#69]
When I use IQKeyboardManager with IQDropDownTextField I am getting this error : 

Undefined symbols for architecture armv7:
  "_CACurrentMediaTime", referenced from:
      -[IQKeyboardManager adjustFrame] in IQKeyboardManager.o
      -[IQKeyboardManager keyboardWillShow:] in IQKeyboardManager.o
      -[IQKeyboardManager keyboardDidShow:] in IQKeyboardManager.o
      -[IQKeyboardManager keyboardWillHide:] in IQKeyboardManager.o
      -[IQKeyboardManager keyboardDidHide:] in IQKeyboardManager.o
      -[IQKeyboardManager textFieldViewDidBeginEditing:] in IQKeyboardManager.o
      -[IQKeyboardManager textFieldViewDidEndEditing:] in IQKeyboardManager.o
      ...
ld: symbol(s) not found for architecture armv7

**Comment by hackiftekhar** [comment]
This might be because CACurrentMediaTime method is used in IQKeyboardManager. Can you please try adding QuartzCore library to your project and see if this solve the issue?

**Comment by Prabhat-Emorphis** [comment]
I add QuartzCore and run the project it build and run successfully but IQKeyboardManager toolabr forward and backward button are not visible, 

You can check it by adding  IQKeyboardManager folder in IQDropDownTextField demo project. It is not working with IQKeyboardManager.

**Comment by hackiftekhar** [comment]
If you check IQKeyboardManager demo project, there I demoed IQDropDownTextField and it's appearing there. Can you please verify that IQDropDownTextField.inputAccessoryView is not already assigned with something else or it does have some view?

**Comment by ginppian** [comment]
for IQKeyboardManager just install it and use it, thats all. You can mix with IQDropDownTextField without worry for IQKeyboardManager
