### ISSUE TITLE
awakeFromNib

### ISSUE THREAD

**Issue by Sooongz** [hackiftekhar/IQDropDownTextField#70]
`
@property (weak, nonatomic) IBOutlet IQDropDownTextField *servedTimeTextField;

- (void)configureView {
    
    self.servedTimeTextField.timeFormatter = [NSDateFormatter dateFormatterWithFormat:@"HH:mm" timeZone:[NSTimeZone timeZoneWithName:@"GMT"] locale:[[NSLocale alloc] initWithLocaleIdentifier:@"en_FR"]];
    self.servedTimeTextField.dropDownMode = IQDropDownModeTimePicker;
    self.servedTimeTextField.keyboardDistanceFromTextField = 250;
}

- (void)awakeFromNib {
    [super awakeFromNib];
    
    //    [self configureView];
}`

When I  initialize the textField user XIB, I found the textField's 'awakeFromNib' run after my view's 'awakeFromNib', so the 'configureView' can not work well.

Is there a problem with the way I use it.

Thx

**Comment by hackiftekhar** [comment]
@Sooongz I think the iOS is doing fine that awakeFromNib of main view call first and then call other awakeFromNib. Can you please verify if textField object is initialized in configureView method or it's still nil?

**Comment by Sooongz** [comment]
Yes, the  textField object has initialized.

**Comment by hackiftekhar** [comment]
If this is the case then I think all is reset with `- (void)initialize` method. I need to check if I can fix that.

**Comment by Sooongz** [comment]
@hackiftekhar Thx
