### ISSUE TITLE
TextFields very slowly

### ISSUE THREAD

**Issue by Sooongz** [hackiftekhar/IQDropDownTextField#71]
I push to UiViewController ( with a tableView),  the tableView has a lot of textFields, when I 'setMinimumDate' and 'setMinimumDate' ,  the push action needs a few seconds.

Is there a problem with the way I use it?

Thx

**Comment by Sooongz** [comment]
When I modify the setMinimumDate method like this, the push action become quickly.

`- (void)setMinimumDate:(NSDate *)minimumDate {
    _minimumDate = minimumDate;
    
    switch (self.dropDownMode) {
        case IQDropDownModeTimePicker:
            self.timePicker.minimumDate = minimumDate;
            break;
        case IQDropDownModeDatePicker:
            self.datePicker.minimumDate = minimumDate;
            break;
        case IQDropDownModeDateTimePicker:
            self.dateTimePicker.minimumDate = minimumDate;
            break;
    }
}
`

**Comment by hackiftekhar** [comment]
I've now removed setMinimumDate property because we are now exposing UIDatePicker objects and this can be directly set there according to requirements.
