### ISSUE TITLE
can setIsOptionalDropDown do nothing in timer or date picker case.

### ISSUE THREAD

**Issue by sameer4** [hackiftekhar/IQDropDownTextField#72]
i have a dropdown in IQDropDownModeDateTimePicker for which i want to setIsOptionalDropDown based on some conditions.so i want dropdown textfield's text to become @"" when it's optional YES and i set .selectedItem = @""
i'm modifying the library files but could you also support this so if someone updates the library, the functionality remains working?

**Comment by sameer4** [comment]
for now i'm doing this.

`if (sender.selected)
    {
        self.txtTimeForSchedule.isOptionalDropDown = YES;
        self.txtTimeForSchedule.dropDownMode = IQDropDownModeTextField;
        self.txtTimeForSchedule.selectedItem = @"";
    }
    else
    {
        self.txtTimeForSchedule.isOptionalDropDown = NO;
        self.txtTimeForSchedule.dropDownMode = IQDropDownModeDateTimePicker;
        self.txtTimeForSchedule.minimumDate = [NSDate date];
        self.txtTimeForSchedule.date = [NSDate date];
        [self.txtTimeForSchedule becomeFirstResponder];
    }`

**Comment by hackiftekhar** [comment]
It's expected because it only applies for a list with library, not with date and time.

**Comment by hackiftekhar** [comment]
@sameer4 I optimized isOptionalDropDown to also work with date and time pickers, please take a look.

**Comment by sameer4** [comment]
thank you
