### ISSUE TITLE
Selected value

### ISSUE THREAD

**Issue by kishorehvk** [hackiftekhar/IQDropDownTextField#73]
Hi , I  am using your library in uitableview. I have created one textfield (iqdropdowntextfield) in a cell and I am dynamically adding upto 5 textfields with different values. If I cancel the row, the textfield values are not canceling while I add again the cancelled values are populating. How to delete the value. Thanks in advance.

**Comment by hackiftekhar** [comment]
You can set it's selectedItem property to nil and it will remove the currently selected value.
