### ISSUE TITLE
How can i set the value in textFiled because using the selectedItem property is not setting the value from dictionary. ex (self.tf_userName.selectedItem = myDict["name"] as? String)..because (.text) property not working here.

### ISSUE THREAD

**Issue by sumit-10** [hackiftekhar/IQDropDownTextField#74]

**Comment by hackiftekhar** [comment]
Yiu should first set the array of item list only after that you can use selectedItem. This limitation is because the library only allow to set value from the predefined list set as item list and user is not allowed to set any text directly using .text property..
