### ISSUE TITLE
Button done.

### ISSUE THREAD

**Issue by fsaldivarids** [hackiftekhar/IQDropDownTextField#81]
Hi, I have a question.
My button done, always has color withe ios 11.

How to change the color button done?

**Comment by hackiftekhar** [comment]
Please try assigning toolbarTintColor to some color

**Comment by fsaldivarids** [comment]
Hi, this problem was solved, 
My solution
UIBarButtonItem.appearance().setTitleTextAttributes([
            NSForegroundColorAttributeName : WIBEColors.DARK,
            NSFontAttributeName : WIBEFonts.getBaseFont(20)
            ], for: UIControlState())


but, I have to change my button for an image

**Comment by hackiftekhar** [comment]
Then you can do something like this

    [[UIBarButtonItem appearanceWhenContainedInInstancesOfClasses:@[[UINavigationBar class]]] setTitleTextAttributes:@{NSForegroundColorAttributeName:[UIColor whiteColor]} forState:UIControlStateNormal];
