### ISSUE TITLE
setMinimumDate not working after new pod update

### ISSUE THREAD

**Issue by hasidil** [hackiftekhar/IQDropDownTextField#82]
setMinimumDate not working after new pod update.

> No visible @interface for 'BHDropDownTextField' declares the selector 'setMinimumDate:'

`NSDate *minimumDate = [NSDate date];
    [self.tfDate setMinimumDate:minimumDate];`

**Comment by hackiftekhar** [comment]
Sorry for inconvenience, with latest version there are UIDatePicker exposed properties

@property (nonnull, nonatomic, readonly) UIDatePicker *datePicker;
@property (nonnull, nonatomic, readonly) UIDatePicker *timePicker;
@property (nonnull, nonatomic, readonly) UIDatePicker *dateTimePicker;

and now you can set minimum date directly there.

**Comment by Mamtak1811** [comment]
How do we use these properties to set minimum and maximum date? Please elaborate

**Comment by hackiftekhar** [comment]
like `[textField.datePicker setMinimumDate:minimumDate]` @Mamtak1811

**Comment by Hardiktspaceo** [comment]
@hackiftekhar how can i set maximum date in latest version v1.1.1, i can't set maximum valid date in this.. can we set maximum date  ?

**Comment by hackiftekhar** [comment]
Yes, you can use my suggestion using v1.1.1

**Comment by Hardiktspaceo** [comment]
In swift i can't set minimum date as per your suggestion can you provide some example for swift version ?

**Comment by hackiftekhar** [comment]
Are you able to access `textField.datePicker` object?

**Comment by Hardiktspaceo** [comment]
ok thank you so much, now i can get access of minimum and maximum date as per your above comment. Thank you so much for quick reply.

**Comment by hackiftekhar** [comment]
Thanks sir!
