### ISSUE TITLE
Button dont you see the first time

### ISSUE THREAD

**Issue by fsaldivarids** [hackiftekhar/IQDropDownTextField#83]
The problem is in ios 11, the toolbar not have button done, 
i need touch two times
mi code

func textFieldShouldBeginEditing(_ textField: UITextField) -> Bool {
        if PaymentsSearchBar.countOpenDate < 4 {
            PaymentsSearchBar.countOpenDate = PaymentsSearchBar.countOpenDate + 1
            textField.reloadInputViews()
            textField.keyboardToolbar.sizeToFit()
            textField.sizeToFit()
            textField.keyboardToolbar.reloadInputViews()
            textField.resignFirstResponder()
        }
        return true
    }

**Comment by fsaldivarids** [comment]
Example first Touch
IQKeyboardManager
![image](https://user-images.githubusercontent.com/29437425/32023993-a5dae560-b9a0-11e7-9acd-450f21a63a96.png)
example first Touch
IQDropDownTextField

![image](https://user-images.githubusercontent.com/29437425/32024021-bc0106f8-b9a0-11e7-9fbf-6bb42fb97cb1.png)

Example second touch
![image](https://user-images.githubusercontent.com/29437425/32024054-d9bf18d8-b9a0-11e7-8760-fe2dfcd5d4fe.png)

**Comment by fsaldivarids** [comment]
Exmaple first touch
<img width="768" alt="captura de pantalla 2017-10-25 a la s 7 14 43 p m" src="https://user-images.githubusercontent.com/29437425/32029242-ebf2d2e8-b9b8-11e7-9ad7-8a9e18cfd1a3.png">

Second touch
<img width="416" alt="captura de pantalla 2017-10-25 a la s 7 15 13 p m" src="https://user-images.githubusercontent.com/29437425/32029248-f67ef2aa-b9b8-11e7-81dc-7a5118e12ea2.png">

**Comment by hackiftekhar** [comment]
Which version of library you are using currently?

**Comment by hackiftekhar** [comment]
can you please try setting translateAutoresizingMaskIntoConstraints property to NO?

**Comment by arqambutt** [comment]
i am also having the same issue and i am using 1.1.1 version of this library

**Comment by fsaldivarids** [comment]
Update last version, my error was the navigation.
