### ISSUE TITLE
How to set selectedItem = nil for Dropdown no optional Item

### ISSUE THREAD

**Issue by LamTranHoang** [hackiftekhar/IQDropDownTextField#90]
![screen shot 2018-08-24 at 5 21 23 pm](https://user-images.githubusercontent.com/42671429/44579893-29b4aa00-a7c2-11e8-9ff6-9564ca9ddc87.png)
i have dropdown
isOptionalDropDown = false

I try to set selectedItem = nil but it always selects the first item

**Comment by hackiftekhar** [comment]
It's because you set `isOptionalDropDown = false` which means the field shouldn't be empty. It's a feature not bug.
