### ISSUE TITLE
Issue with the selection of 2 items with same name

### ISSUE THREAD

**Issue by sameer4** [hackiftekhar/IQDropDownTextField#91]
I have have a case in my app where item list contains 2 items with same name and if i try to select first item. itemdropdown scrollbacks to first item so second item selection is not possible. can you please solve it?

**Comment by hackiftekhar** [comment]
It cannot be solved very easily since I need to do a lot of code changes. For a workaround how about giving space as prefix and postfix for second text? For example "Test" can be replaced as " Test ".
