### ISSUE TITLE
PickerView hiding Automatically after the execution of didSelectItem

### ISSUE THREAD

**Issue by MohanRamanathan** [hackiftekhar/IQDropDownTextField#92]
#import "IQDropDownTextField.h"
@property (weak, nonatomic) IBOutlet IQDropDownTextField *quantity;

static id<IQDropDownTextFieldDelegate> quantityDelegate; 

+(CartProductTableViewCell *)generateProductCell:(UITableView *)tableView TableView:(Product *)product Product:(NSIndexPath *)indexPath {
    cell.quantity.isOptionalDropDown = NO;
    NSMutableArray  * items = [[NSMutableArray alloc]init];
    for (int i = 1; i <= ([product stock_count]); i++) {
        [items addObject:[NSString stringWithFormat:@"%d",i]];
    }
    cell.quantity.delegate = quantityDelegate;
    if ([items count] != 0) {
        [cell.quantity setItemList:items];
        if ([[product quantity] intValue] <= [product stock_count]) {
            [cell.quantity setSelectedRow:[[product quantity] intValue]-1];
        }
    }
}
-(void)textField:(nonnull IQDropDownTextField*)textField didSelectItem:(nullable NSString*)item {
    [delegate notifyProductQuantityChanged:mProduct WithQuantity:[textField selectedItem] WithIndexPath:_mIndexPath];
}

in the didSelectItem delegate method i am using the delegate method which i created, it will pass the value through that and complete the function in the Parent class. After that the PickerView is getting hided automatically without pressing the Done button.

I need to stop this automatically hiding PickerView. When the user pressing the Done button then only the PickerView should get hide.

Edit: I found that textFieldViewDidEndEditing is getting called in IQKeyboardManager.m, After the execution of that method only the keyboard is getting hided.

**Comment by hackiftekhar** [comment]
@MohanRamanathan you might be triggering [endsEditing: true] or resignFirstResponder somewhen in your code. Both libraries do not automatically dismiss the keyboard/dropdown.
