### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by mobicity** [hackiftekhar/IQDropDownTextField#93]
I've got this issue in my application 
<img width="1110" alt="Screen Shot 2019-04-24 at 10 16 39" src="https://user-images.githubusercontent.com/43755722/56901078-a98bc600-6a6d-11e9-9f2d-dd2ee18836f7.png"> that is stating that IQDropDownTextField is leaking memory! @hackiftekhar , can you help me?

**Comment by gask** [comment]
@hackiftekhar Have you figured out what is causing this?

**Comment by hackiftekhar** [comment]
Nope, I wasn't able to figure it out. I need a demo project here since I don't know what is happening at your code.
