### ISSUE TITLE
Set Selected Row index out of range

### ISSUE THREAD

**Issue by developerawais** [hackiftekhar/IQDropDownTextField#97]
<img width="1415" alt="Screenshot 2019-12-05 at 11 34 52 AM" src="https://user-images.githubusercontent.com/58505784/70210143-c0a53b80-1753-11ea-8217-9c6f8b65c0e1.png">

**Comment by hackiftekhar** [comment]
Have you set any itemList before setting selectedItem.

**Comment by developerawais** [comment]
Resolved
