### ISSUE TITLE
IQDropDownTextField is still typeable 

### ISSUE THREAD

**Issue by destantifw** [hackiftekhar/IQDropDownTextField#98]
How can i disable typing in IQDropDownTextField while userInteraction is still enabled and picker is still shown?
![Screen Shot 2020-01-02 at 14 01 19](https://user-images.githubusercontent.com/14884055/71655199-65716380-2d68-11ea-9629-c59413d7fc46.png)

**Comment by hackiftekhar** [comment]
You can't type, cut or paste text there, it's just a selection of text and other options which doesn't change text.
