### ISSUE TITLE
Multiple Components Support

### ISSUE THREAD

**Issue by ankahathara** [hackiftekhar/IQDropDownTextField#99]
Is there way to have multiple components for the picker view?

I have a requirement which is to have two components in the picker, One componet is to show number from 1 to 30 and other components should say Days, Weeks, Months, and Years.

Is there easy way to make this happen in the library?

Thank you.

**Comment by hackiftekhar** [comment]
There is no such feature right now, you could try using the `IQActionSheetPickerView` for this kind of feature.
